=== savra57/graph2svg/test/e2e/osgr/osgr.dtd
<!ELEMENT osgr (title?, names?, values+)>
<!ELEMENT names (name+)>
<!ELEMENT values (value+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST osgr 
			xmlns CDATA #FIXED "http://graph2svg.googlecode.com"
			graphType (pie|norm) "norm"
			effect (2D|3D) "2D"
			colType  (none|block|cylinder|cone|pyramid|line) "block"
			lineType (none|solid|dot|dash|longDash|dash-dot|longDash-dot|dash-dot-dot|longDash-dash|dash-dash-dot-dot) "none"
			pointType (none|point|cross|plus|minus|star|square|circle|triangle|rhomb|pyramid|squareF|circleF|triangleF|rhombF|pyramidF) "none"
			smooth (yes|no) "no"
			
			xAxisDivision  (none|major|minor|both) "minor"
			xAxisPos (bottom|origin) "origin"
			xGrid (none|major|minor|both) "none"
			categoryGap CDATA #IMPLIED
			columnWd CDATA #IMPLIED
			
			yAxisType  (auto|withZero|shifted|log|dateTime) "auto"
			yAxisDivision  (none|1|2|4|5|10) "1"
			yGrid (none|major|minor) "none"
			yAxisLabelsFormat CDATA #IMPLIED
			yAxisMin CDATA #IMPLIED
			yAxisMax CDATA #IMPLIED
			yAxisStep CDATA #IMPLIED
			yAxisMarkCount CDATA #IMPLIED
			yAxisMarkDist CDATA #IMPLIED
			
			legend  (none|left|right|top|bottom) "none"
			legendMargin CDATA #IMPLIED
			legendPictureWd CDATA #IMPLIED
			legendPictureHg CDATA #IMPLIED
			legendLineHg CDATA #IMPLIED
			legendGap CDATA #IMPLIED
			legendFontSize CDATA #IMPLIED
			
			graphMargin CDATA #IMPLIED
			titleMargin CDATA #IMPLIED
			titleFontSize CDATA #IMPLIED
			
			labelAngle CDATA #IMPLIED
			labelFontSize CDATA #IMPLIED
			labelIn (none|value|percent|name) "none"
			labelOut (none|value|percent|name) "none"
			
			colorScheme  (color|warm|cold|grey|black) "color">
<!ATTLIST title color CDATA #IMPLIED>
<!ATTLIST value
			color CDATA #IMPLIED
			pointType (none|point|cross|plus|minus|star|square|circle|triangle|rhomb|pyramid|squareF|circleF|triangleF|rhombF|pyramidF) #IMPLIED>

=== savra57/graph2svg/test/e2e/osgr/t_default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE osgr SYSTEM "osgr.dtd">
<osgr xmlns="http://graph2svg.googlecode.com"
		>
	<title>Default 1</title>
	<names>
		<name>Monday</name>
		<name>Tuesday</name>
	     <name>Wednesday</name>
    </names>
    <values>
            <value>12</value>
            <value>45</value>
            <value>30</value>
    </values>
</osgr>

=== savra57/graph2svg/test/e2e/osgr/t_markCountWithMax.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE osgr SYSTEM "osgr.dtd">
<osgr xmlns="http://graph2svg.googlecode.com"
		yAxisMarkCount="5" yAxisMax="40">
	<title>User mark count and max</title>
	<names>
		<name>Mon</name>
		<name>Tue</name>
		<name>Wed</name>
		<name>Thu</name>
		<name>Fri</name>
	</names>
	<values>
		<value>41</value>
		<value>38</value>
		<value>30</value>
		<value>40</value>
		<value>32</value>
	</values>
</osgr>

=== savra57/graph2svg/test/e2e/osgr/t_timeY_hours.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE osgr SYSTEM "osgr.dtd">
<osgr xmlns="http://graph2svg.googlecode.com"
		yAxisType="dateTime"
		yAxisLabelsFormat="[MN,*-3] [D01] [h02]:[m01]"
		colorScheme="grey">
	<names>
		<name>1</name>
		<name>2</name>
		<name>3</name>
		<name>4</name>
		<name>5</name>
		<name>6</name>
		<name>7</name>
		<name>8</name>
		<name>9</name>
		<name>10</name>
		<name>11</name>
		<name>12</name>
		<name>14</name>
	</names>
	<values>
		<value>2010-01-21T11:12:04</value>
		<value>2010-01-21T14:04:00</value>
		<value>2010-01-22T01:35:00</value>
		<value>2010-01-21T23:50:04</value>
		<value>2010-01-21T18:00:30</value>
		<value>2010-01-21T16:40:00</value>
		<value>2010-01-21T14:40:00</value>
		<value>2010-01-21T17:00:00</value>
		<value>2010-01-21T16:00:00</value>
		<value>2010-01-21T15:00:00</value>
		<value>2010-01-21T14:00:00</value>
		<value>2010-01-21T13:00:00</value>
		<value>2010-01-21T12:00:00</value>
	</values>
	
</osgr>

=== savra57/graph2svg/test/e2e/osgr/t_columns_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE osgr SYSTEM "osgr.dtd">
<osgr xmlns="http://graph2svg.googlecode.com"
		colorScheme="warm" labelIn="percent" labelOut="name" 
		yAxisDivision="2"  xAxisDivision="none" pointType="circle" effect="3D"
		xAxisPos="bottom" legend="right">
	<title>Pokusný graf číslo 4 - sloupce</title>
	<names>
		<name>Leden</name>
		<name>Únor</name>
	     <name>Březen</name>
	     <name>Duben</name>
		<name>Květen</name>
    </names>
    <values>
            <value>12</value>
            <value>6</value>
            <value>3</value>
            <value>12</value>
            <value>24</value>
    </values>
</osgr>

=== savra57/graph2svg/test/e2e/osgr/t_logAxis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE osgr SYSTEM "osgr.dtd">
<osgr xmlns="http://graph2svg.googlecode.com"
		yAxisType="log">
	<title>Logaritmic axis</title>
	<names>
		<name>Mon</name>
		<name>Tue</name>
		<name>Wed</name>
		<name>Thu</name>
		<name>Fri</name>
	</names>
	<values>
		<value>90</value>
		<value>-10</value>
		<value>0.09564</value>
		<value>0.001564</value>
		<value>0.0001</value>
	</values>
</osgr>
