=== savra57/graph2svg/test/e2e/msgr/msgr.dtd
<!ELEMENT msgr (title?, names?, values+)>
<!ELEMENT names (name+)>
<!ELEMENT values (title?, value+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST msgr 
			xmlns CDATA #FIXED "http://graph2svg.googlecode.com"
			stacked (none|sum|percentage) "none"
			shift CDATA "0"
			effect (2D|3D) "2D"
			colType  (none|block|cylinder|cone|pyramid|line) "none"
			lineType (none|solid|dot|dash|longDash|dash-dot|longDash-dot|dash-dot-dot|longDash-dash|dash-dash-dot-dot) "solid"
			pointType (none|point|cross|plus|minus|star|square|circle|triangle|rhomb|pyramid|squareF|circleF|triangleF|rhombF|pyramidF) "none"
			fillArea  (yes|no) "no"
			
			xAxisDivision  (none|major|minor|both) "minor"
			xAxisPos (bottom|origin) "origin"
			xGrid (none|major|minor|both) "none"
			
			yAxisType  (auto|withZero|shifted|log|dateTime) "auto"
			yAxisDivision  (none|1|2|4|5|10) "1"
			yGrid (none|major|minor) "none"
			yAxisLabelsFormat CDATA #IMPLIED
			yAxisMin CDATA #IMPLIED
			yAxisMax CDATA #IMPLIED
			yAxisStep CDATA #IMPLIED
			yAxisMarkCount CDATA #IMPLIED
			
			legend  (none|left|right|top|bottom) "right"
			colorScheme  (color|warm|cold|grey|black) "color">
<!ATTLIST title color CDATA #IMPLIED>
<!ATTLIST values 
			color CDATA #IMPLIED
			colType  (none|block|cylinder|cone|pyramid|line) #IMPLIED
			lineType (none|solid|dot|dash|longDash|dash-dot|longDash-dot|dash-dot-dot|longDash-dash|dash-dash-dot-dot) #IMPLIED
			pointType (none|point|cross|plus|minus|star|square|circle|triangle|rhomb|pyramid|squareF|circleF|triangleF|rhombF|pyramidF) #IMPLIED
			smooth (yes|no) "no"
			fillArea  (yes|no) #IMPLIED
			startFrom (axis|last) #IMPLIED>

=== savra57/graph2svg/test/e2e/msgr/w_dev.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE msgr SYSTEM "msgr.dtd">
<msgr xmlns="http://graph2svg.googlecode.com"
    colorScheme="black" lineType="none">
  <title>Columns with deviations</title>
  <names>
    <name>Jan</name>
    <name>Feb</name>
    <name>Mar</name>
    <name>Apr</name>
    <name>May</name>
    <name>Jun</name>
  </names>
  <values colType="block" color="#888">
    <title>columns: colType="block" color="#888"</title>
    <value>118</value>
    <value>121</value>
    <value>122</value>
    <value>123</value>
    <value>121</value>
    <value>120</value>
  </values>
  <values>
    <title>botom of lines: none</title>
    <value>117</value>
    <value>119</value>
    <value>119.7</value>
    <value>121.4</value>
    <value>119.4</value>
    <value>119.5</value>
  </values>
  <values colType="line" startFrom="last">
    <title>top of lines: colType="line" startFrom="last"</title>
    <value>119</value>
    <value>121.9</value>
    <value>123.1</value>
    <value>124.8</value>
    <value>122.8</value>
    <value>121.1</value>
  </values>
  <values pointType="minus">
    <title>expected value: pointType="minus"</title>
    <value>117.8</value>
    <value>120.5</value>
    <value>121.8</value>
    <value>123.4</value>
    <value>120.35</value>
    <value>120.25</value>
  </values>
</msgr>

=== savra57/graph2svg/test/e2e/msgr/t_negative3DColumns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE msgr SYSTEM "msgr.dtd">
<msgr xmlns="http://graph2svg.googlecode.com" 
	lineType="none" effect="3D" shift="1.5" yAxisStep="100"
	xAxisDivision="both" xGrid="both" yGrid="major" 
	legend="left">
	<title>3D columns with negative values</title>
	<names>
		<name>Positive</name>
		<name>Negative</name>
	</names>

	<values colType="block">
		<title>block</title>
		<value>1300</value>
		<value>-600</value>
	</values>
	<values colType="cylinder">
		<title>cylinder</title>
		<value>900</value>
		<value>-300</value>
	</values>
	<values colType="cone">
		<title>cone</title>
		<value>1100</value>
		<value>-500</value>
	</values>
	<values colType="pyramid">
		<title>pyramid</title>
		<value>600</value>
		<value>-200</value>
	</values>
	<values colType="block" startFrom="last">
		<title>block last</title>
		<value>200</value>
		<value>-500</value>
	</values>
	<values colType="cylinder" startFrom="last">
		<title>cylinder last</title>
		<value>800</value>
		<value>-100</value>
	</values>
	<values colType="cone" startFrom="last">
		<title>cone last</title>
		<value>600</value>
		<value>-200</value>
	</values>
	<values colType="pyramid" startFrom="last">
		<title>pyramid last</title>
		<value>1100</value>
		<value>0</value>
	</values>
</msgr>

=== savra57/graph2svg/test/e2e/msgr/w_area.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE msgr SYSTEM "msgr.dtd">
<msgr xmlns="http://graph2svg.googlecode.com"
		stacked="sum" lineType="none" 
		fillArea="yes" colorScheme="cold"
	>
  <title>Production</title>
  <names>
    <name>Jan</name>
    <name>Feb</name>
    <name>Mar</name>
    <name>Apr</name>
    <name>May</name>
    <name>Jun</name>
  </names>
  <values>
    <title>product A</title>
    <value>21</value>
    <value>22</value>
    <value>18</value>
    <value>18</value>
    <value>16</value>
    <value>14</value>
  </values>
  <values>
    <title>product B</title>
    <value>10</value>
    <value>12</value>
    <value>9</value>
    <value>11</value>
    <value>15</value>
    <value>18</value>
  </values>
  <values>
    <title>product C</title>
    <value>28</value>
    <value>29</value>
    <value>22</value>
    <value>25</value>
    <value>30</value>
    <value>25</value>
  </values>
</msgr>

=== savra57/graph2svg/test/e2e/msgr/t_sizes_noMargins.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE msgr SYSTEM "msgr.dtd">
<msgr xmlns="http://graph2svg.googlecode.com" colType="block" lineType="none" legend="right" xAxisDivision="both" shift="1.5"
	yAxisDivision="2" effect="3D" graphMargin="0" titleMargin="0" legendMargin="0">
	<title>Sizes - No Margins</title>
	<names>
		<name>Spring</name>
		<name>Summer</name>
		<name>Autumn</name>
	</names>

	<values color="#c5a712">
		<title>Pears Net Export</title>
		<value>5</value>
		<value>30</value>
		<value>-15</value>
	</values>
	<values color="#d82914">
		<title>Apples Net Export</title>
		<value>15</value>
		<value>50</value>
		<value>89</value>
	</values>
</msgr>

=== savra57/graph2svg/test/e2e/msgr/t_logAxis_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE msgr SYSTEM "msgr.dtd">
<msgr xmlns="http://graph2svg.googlecode.com"
			colType="none" legend="top" xAxisDivision="both" shift="0" yAxisDivision="5"
			pointType="star" colorScheme="cold" xGrid='both' yGrid='minor' effect='3D' lineType="solid" 
			xAxisPos="bottom" yAxisType="log">
	<title>Pokusný graf číslo 2 - log osa</title>
	<names>
		<name>Leden</name>
		<name>Únor</name>
	     <name>Březen</name>
	     <name>Duben</name>
	     <name>Květen</name>
	     <name>Červen</name>
	     <name>Červenec</name>
	     <name>Srpen</name>
	     <name>Září</name>
		<name>Říjen</name>
		<name>Listopad</name>
		<name>Prosinec</name>
    </names>
	<values>
		<title>small values</title>
		<value>0.0005</value>
		<value>0.008</value>
		<value>0.02</value>
		<value>0.3</value>
		<value>0.95</value>
		<value>10</value>
		<value>100</value>
		<value>5000</value>
		<value>9800</value>
		<value>40000</value>
	</values>
	<values>
		<title>big values</title>
		<value>90000</value>
		<value>10000</value>
		<value>4000</value>
		<value>90</value>
		<value>1</value>
		<value>10</value>
		<value>120</value>
		<value>1250</value>
		<value>8000</value>
		<value>15000</value>
     </values>
</msgr>

=== savra57/graph2svg/test/e2e/msgr/t_sizes_wideLegendColumnsGaps.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE msgr SYSTEM "msgr.dtd">
<msgr xmlns="http://graph2svg.googlecode.com" colType="block" lineType="none" legend="right" xAxisDivision="both" shift="1.5"
	yAxisDivision="2" effect="3D" categoryGap="40" columnWd="40"
	legendPictureWd="52" legendPictureHg="40" legendLineHg="80" legendGap="40">
	<title>Sizes - Big Legend, Wide Columns and Gaps</title>
	<names>
		<name>Spring</name>
		<name>Summer</name>
		<name>Autumn</name>
	</names>

	<values color="#c5a712">
		<title>Pears Net Export</title>
		<value>5</value>
		<value>30</value>
		<value>-15</value>
	</values>
	<values color="#d82914">
		<title>Apples Net Export</title>
		<value>15</value>
		<value>50</value>
		<value>89</value>
	</values>
</msgr>

=== savra57/graph2svg/test/e2e/msgr/t_negative3DStacked.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE msgr SYSTEM "msgr.dtd">
<msgr xmlns="http://graph2svg.googlecode.com"
stacked="sum" lineType="none" 
colType="block" effect="3D" 
yGrid="major" yAxisMarkCount="7">
  <title>Sum - Different 3D Columns</title>
  <names>
    <name>Jan</name>
    <name>Feb</name>
    <name>Mar</name>
    <name>Apr</name>
    <name>May</name>
    <name>Jun</name>
  </names>
  <values>
    <title>Block</title>
    <value>21</value>
    <value>22</value>
    <value>15</value>
    <value>18</value>
    <value>16</value>
    <value>14</value>
  </values>
  <values colType="pyramid">
    <title>Pyramid</title>
    <value>10</value>
    <value>12</value>
    <value>-18</value>
    <value>11</value>
    <value>15</value>
    <value>18</value>
  </values>
  <values colType="cone">
    <title>Cone</title>
    <value>28</value>
    <value>29</value>
    <value>32</value>
    <value>25</value>
    <value>30</value>
    <value>25</value>
  </values>
</msgr>

=== savra57/graph2svg/test/e2e/msgr/t_timeY_mins.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE msgr SYSTEM "msgr.dtd">
<msgr xmlns="http://graph2svg.googlecode.com"
		legend="top"
		yAxisType="dateTime"
		yAxisLabelsFormat="[h02]:[m01]:[s01]"
		lineType="solid"
		pointType="point">
			
	<title>Marathon World Records</title>
	
	<names>
		<name>1926</name>
		<name>1970</name>
		<name>1981</name>
		<name>1999</name>
		<name>2003</name>
		<name>2011</name>
	</names>
	
	<values color="violet">
		<title>Women</title>
		<value>2010-01-01T03:40:22</value>
		<value>2010-01-01T03:02:53</value>
		<value>2010-01-01T02:29:57</value>
		<value>2010-01-01T02:20:43</value>
		<value>2010-01-01T02:15:25</value>
		<value>2010-01-01T02:15:25</value>
	</values>
	
	<values color="blue">
		<title>Men</title>
		<value>2010-01-01T02:29:02</value>
		<value>2010-01-01T02:09:29</value>
		<value>2010-01-01T02:08:18</value>
		<value>2010-01-01T02:05:42</value>
		<value>2010-01-01T02:04:55</value>
		<value>2010-01-01T02:03:38</value>
	</values>
	
</msgr>
