=== savra57/graph2svg/scripts/xygr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT xygr (title?, curve+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT curve (name?, point+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT point EMPTY>
<!ATTLIST xygr 
			xmlns CDATA #FIXED "http://graph2svg.googlecode.com"
			lineType (none|solid|dot|dash|longDash|dash-dot|longDash-dot|dash-dot-dot|longDash-dash|dash-dash-dot-dot) "solid"
			pointType  (none|point|cross|plus|line|star|square|circle|triangle|rhomb|pyramid|squareF|circleF|triangleF|rhombF|pyramidF) "none"
			axesPos (left-bottom|origin) "origin"
			
			xAxisType  (auto|withZero|shifted|log|dateTime) "auto"
			xAxisDivision  (none|1|2|4|5|10) "1"
			xGrid  (none|major|minor) "none"
			xAxisLabelsFormat CDATA #IMPLIED
			xAxisMin CDATA #IMPLIED
			xAxisMax CDATA #IMPLIED
			xAxisStep CDATA #IMPLIED
			xAxisMarkCount CDATA #IMPLIED
			
			yAxisType  (auto|withZero|shifted|log|dateTime) "auto"
			yAxisDivision  (none|1|2|4|5|10) "1"
			yGrid  (none|major|minor) "none"
			yAxisLabelsFormat CDATA #IMPLIED
			yAxisMin CDATA #IMPLIED
			yAxisMax CDATA #IMPLIED
			yAxisStep CDATA #IMPLIED
			yAxisMarkCount CDATA #IMPLIED
			
			legend  (none|left|right|top|bottom) "none"
			colorScheme  (color|warm|cold|grey|black) "black">
<!ATTLIST curve 
			lineType  (none|solid|dot|dash|longDash|dash-dot|longDash-dot|dash-dot-dot|longDash-dash|dash-dash-dot-dot) #IMPLIED
			smooth (yes|no) "no"
			pointType (none|point|cross|plus|line|star|square|circle|triangle|rhomb|pyramid|squareF|circleF|triangleF|rhombF|pyramidF) #IMPLIED
			color  CDATA #IMPLIED>
<!ATTLIST name
			x  CDATA #IMPLIED
			y  CDATA #IMPLIED
			color  CDATA #IMPLIED
			visibility (none|legend|graph|both) "both">
<!ATTLIST point
			x  CDATA #REQUIRED
			y  CDATA #REQUIRED
			pointType  (none|point|cross|plus|line|star|square|circle|triangle|rhomb|pyramid|squareF|circleF|triangleF|rhombF|pyramidF) #IMPLIED
			color  CDATA #IMPLIED>

=== savra57/graph2svg/test/e2e/xygr/t_timeX_sec.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xygr SYSTEM "xygr.dtd">
<xygr xmlns="http://graph2svg.googlecode.com"
		pointType="circle" colorScheme="cold"
		axesPos="left-bottom"
		xAxisType="dateTime"> 
	<title>Test 15 seconds on X</title>

	<curve>
		<point x="2010-01-22T11:04:04" y="15"/>
		<point x="2010-01-22T11:04:10" y="12"/>
		<point x="2010-01-22T11:04:11" y="10"/>
		<point x="2010-01-22T11:04:12" y="13"/>
		<point x="2010-01-22T11:04:20" y="14"/>
	</curve>

</xygr>

=== savra57/graph2svg/test/e2e/xygr/t_sizes_wideDistances_bigCurveFont.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xygr SYSTEM "xygr.dtd">
<xygr xmlns="http://graph2svg.googlecode.com"
		pointType="point" colorScheme="cold"
		xAxisMarkDist="60" yAxisMarkDist="40" curveFontSize="25">
	<title>Sizes - Wide Distances, Big Curve Font</title>
	<curve smooth="yes">
		<name>Long</name>
		<point x="45" y="4"/>
		<point x="60" y="7"/>
		<point x="65" y="3"/>
		<point x="81" y="6"/>
		<point x="90" y="7"/>
	</curve>
	<curve>
		<name>Short</name>
		<point x="50" y="3"/>
		<point x="55" y="6"/>
		<point x="60" y="8"/>
		<point x="65" y="10"/>
	</curve>
</xygr>

=== savra57/graph2svg/test/e2e/xygr/t_userMinMax_LogAndTime.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xygr SYSTEM "xygr.dtd">
<xygr xmlns="http://graph2svg.googlecode.com"
		lineType="solid" pointType="point"
		xAxisType="dateTime" xAxisLabelsFormat="[H01]h" 
		xAxisMin="2010-01-22T00:00:00" xAxisMax="2010-01-22T24:00:00"
		yAxisType="log" yAxisMax="1000"
	>

	<title>Axes - user max and min for log and time axis</title>
	<curve>
		<point x="2010-01-22T01:30:00" y="50"/>
		<point x="2010-01-22T08:00:10" y="0.002"/>
		<point x="2010-01-22T11:50:11" y="50"/>
		<point x="2010-01-22T18:00:12" y="91"/>
		<point x="2010-01-22T21:01:20" y="10"/>
	</curve>
</xygr>

=== savra57/graph2svg/test/e2e/xygr/t_userStep_LogAndTime.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xygr SYSTEM "xygr.dtd">
<!-- the x step is 30 minutes in seconds 
yAxisMarkCount should be ignored as the step is defined
-->
<xygr xmlns="http://graph2svg.googlecode.com"
		lineType="solid" pointType="point"
		xAxisType="dateTime" xAxisStep="1800"
		yAxisType="log" yAxisStep="2" yAxisMarkCount="20"
	>

	<title>Axes - user step for log and time axis</title>
	<curve>
		<point x="2010-01-22T09:00:00" y="10250"/>
		<point x="2010-01-22T10:30:10" y="5508"/>
		<point x="2010-01-22T11:50:11" y="150"/>
		<point x="2010-01-22T13:00:12" y="0.002"/>
		<point x="2010-01-22T14:29:59" y="10"/>
	</curve>
</xygr>

=== savra57/graph2svg/test/e2e/xygr/t_timeY_weeks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xygr SYSTEM "xygr.dtd">
<xygr xmlns="http://graph2svg.googlecode.com"
		pointType="circle" colorScheme="cold"
		axesPos="left-bottom"
		yAxisType="dateTime~[D01] [MNn] [Y0001]"> 
	<title>Test Weeks on Y</title>

	<curve>
		<point x="120" y="2010-01-22T00:00:00"/>
		<point x="245" y="2010-01-18T00:00:00"/>
		<point x="200" y="2010-02-05T00:00:00"/>
		<point x="325" y="2009-12-29T00:00:00"/>
		<point x="450" y="2009-11-25T00:00:00"/>
		<point x="510" y="2010-01-10T00:00:00"/>
		<point x="600" y="2010-02-20T00:00:00"/>
		<point x="480" y="2010-02-01T00:00:00"/>
	</curve>

</xygr>
